### ISSUE TITLE
[bug]```https://proxy.ayachan.fun/post/bandori/489/info?diff=3```无法正常访问

### ISSUE THREAD

**Issue by WindowsSov8forUs** [6QHTSK/ayachan-bestdoriAPI#2]
通过代码访问```https://proxy.ayachan.fun/post/bandori/495/info?diff=3```出现```Connection to proxy.ayachan.fun timed out```错误，同时通过浏览器直接访问也无法正常访问，应该是```proxy.ayachan.fun```的问题而不是某个单独的ID的问题
部分代码：
```
url = 'https://proxy.ayachan.fun/post/bandori/{}/info?diff=3'.format(songId)
            response = requests.get(url).json()
```
错误信息：
```
HTTPSConnectionPool(host='proxy.ayachan.fun', port=443): Max retries exceeded with url: /post/bandori/495/info?diff=3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021077B17C10>, 'Connection to proxy.ayachan.fun timed out. (connect timeout=None)'))
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 200, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 604, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 209, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000021077B17C10>, 'Connection to proxy.ayachan.fun timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='proxy.ayachan.fun', port=443): Max retries exceeded with url: /post/bandori/495/info?diff=3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021077B17C10>, 'Connection to proxy.ayachan.fun timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\WinNyanBot\misaki_bot.py", line 2271, in dataRefresh
    song.informationRefresh()
  File "C:\Users\Administrator\Desktop\WinNyanBot\misaki_bot.py", line 1360, in informationRefresh
    'source': jacketAndAudioGet(Id, info['jacketImage'][-1]),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\WinNyanBot\misaki_bot.py", line 1313, in jacketAndAudioGet
    response = requests.get(url).json()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='proxy.ayachan.fun', port=443): Max retries exceeded with url: /post/bandori/495/info?diff=3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021077B17C10>, 'Connection to proxy.ayachan.fun timed out. (connect timeout=None)'))
```
彩绫我的彩绫😭😭😭你用工具站扭转了bd自制谱😇😇😇你用```Bestdori-Proxy```统一了bd资源乱象😎😎😎你用你的智慧🧐🧐🧐将邦玩家群体带入了新时代🌟🌟🌟没有你😨😨😨我的代码不复存在👻👻👻没有你😫😫😫我的一切付之东流☠☠☠

**Comment by 6QHTSK** [comment]
服务器到期了，明天我续约，我在现在在改毕设。
不要在这发电（

**Comment by 6QHTSK** [comment]
已续费服务器，服务恢复运行。
